### ISSUE TITLE
v0.2.3: Cannot edit already visited input fields

### ISSUE THREAD

**Issue by funkybunky** [mbrookes/formsy-material-ui#16] opened 2015-11-01 22:18 UTC
I'm having multiple `FormsyText` components and basically just following the example. Reproduction:
- Enter input field
- Type something (or even don't)
- Click onto something else
- Re-visit the field
- Try to edit the field, doesn't change anything

So, as a user, I'm stuck with whatever I've written into the input the first time I visited it.
Any ideas what could cause that issue?
I'm using ES6 class syntax and React v0.14.1, material-ui v0.13.1

**Comment by mbrookes** [comment] 2015-11-01 22:36
It may be related to ES6 class syntax not supporting mixins?

**Comment by funkybunky** [comment] 2015-11-01 23:08
Thanks for the fast response!
Just tried it out using the regular syntax, but the problems persists.

**Comment by mbrookes** [comment] 2015-11-01 23:42
Ah, sorry, this is due to a change that was introduced in 0.2.3 to try to fix a different issues. Please use 0.2.2 for now until we get it fixed, but you might run into some of the  other limitations.

**Comment by funkybunky** [comment] 2015-11-02 00:02
Okay. It works at 0.2.2
Thanks for the help!
I'll leave the issue open for helping others who run into the same issue until it is fixed at the latest version.

**Comment by mbrookes** [comment] 2015-11-02 16:31
Fixed in #19.

**Comment by mbrookes** [comment] 2015-11-03 16:20
I can still reproduce. Best to stick with 0.2.2.

**Comment by mbrookes** [comment] 2015-11-03 16:39
https://github.com/mbrookes/formsy-material-ui/tree/textfield-testcases

**Comment by mbrookes** [comment] 2015-11-03 16:56
Ach, never mind - caching issue. The test cover the other open issue from 0.2.3 / 0.2.4. I'll reference them there.

**Closed by mbrookes** 2015-11-03 16:56 UTC
