### ISSUE TITLE
"onEnterKeyDown" property of "TextField" has been deprecated in material ui

### ISSUE THREAD

**Issue by rnarayan** [mbrookes/formsy-material-ui#70] opened 2016-03-16 02:33 UTC
When using the Example code of formsy-material-ui, I am getting the following error. I am using 0.15.0-alpha.1 version of material-ui.

Warning: "onEnterKeyDown" property of "TextField" has been deprecated.
Use onKeyDown and check for keycode instead.

**Comment by mbrookes** [comment] 2016-03-16 09:52
Dupe of #60.

**Closed by mbrookes** 2016-03-16 09:52 UTC
