### ISSUE TITLE
[FormsyDate, FormsyTime] Input box with label text not clickable

### ISSUE THREAD

**Issue by smithjessk** [mbrookes/formsy-material-ui#95] opened 2016-05-02 19:57 UTC
```javascript
import * as React from "react";
import * as ReactDOM from "react-dom";
const Formsy = require('formsy-react');
const FMUI = require('formsy-material-ui');
const { FormsyDate, FormsyTime } = FMUI;

const props = {
    name: "Test",
    floatingLabelText: "Can't click here"
};
const timeComponent = React.createElement(FormsyTime, props);
const dateComponent = React.createElement(FormsyDate, props);
const form = React.createElement(Formsy.Form, {}, timeComponent, dateComponent);
const root = document.createElement("div");
document.body.appendChild(root);
ReactDOM.render(form, root);
```

Before a value has been entered for these two components, the input dialog is only brought up if you click in the input box but outside of the floating label text. Once a value has been inputted, or a default value has been picked, then you can click on it to bring up the value.

Relevant dependencies are:
```json
"formsy-material-ui": "^0.3.8",
"formsy-react": "^0.17.0",
"material-ui": "^0.14.4",
"react": "^0.14.7",
"react-dom": "^0.14.7",
"typescript": "^1.8.9"
```

**Comment by mbrookes** [comment] 2016-05-02 20:03
Hi @smithjessk Thanks for the detail report - that's almost certainly an issue with Material-UI. Can you test without FMUI, with 0.14.4 and current versions of Material-UI?

**Comment by smithjessk** [comment] 2016-05-02 21:18
```javascript
import * as React from "react";
import * as ReactDOM from "react-dom";
import { DatePicker, TimePicker } from "material-ui";

const props = {
    hintText: "Can't click here"
};
const timeComponent = React.createElement(TimePicker, props);
const dateComponent = React.createElement(DatePicker, props);
const form = React.createElement("div", {}, timeComponent, dateComponent);
const root = document.createElement("div");
window.onload = function() {
    document.body.appendChild(root);
    ReactDOM.render(form, root);    
}
```

Doesn't allow me to click inside the bars at all. What dumb mistake am I making?

**Comment by mbrookes** [comment] 2016-05-02 21:22
Did you test with 0.15.0-beta.2? I only ask because I recognise the bug, and I'm pretty sire it's fixed in more recent versions.

**Comment by smithjessk** [comment] 2016-05-03 14:51
I'm testing it on Material-UI version 0.15.0-beta.1 because:

```
npm ERR! peerinvalid The package material-ui@0.15.0-beta.2 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer formsy-material-ui@0.4.2 wants material-ui@0.15.0-beta.1
```

**Comment by smithjessk** [comment] 2016-05-03 14:52
Fixing some errors in the change right now, will let you know the results.

**Comment by mbrookes** [comment] 2016-05-03 20:13
> npm ERR! peerinvalid Peer formsy-material-ui@0.4.2 wants material-ui@0.15.0-beta.1

Oh, sorry - I need to update that, but it's safe to ignore if your project is using material-ui@0.15.0-beta.2 / or material-ui@next

**Comment by smithjessk** [comment] 2016-05-04 18:14
With this code, I can't click anywhere inside the input dialogs; this includes outside of the label text. Do I need to put them inside a form?

```javascript
import * as React from "react";
import * as ReactDOM from "react-dom";
import { DatePicker, TimePicker } from "material-ui";
const styles = require("material-ui/styles/index");

const props = {
    hintText: "Can't click here"
};

const Root = React.createClass({
    childContextTypes: {
        muiTheme: React.PropTypes.object.isRequired
    },
    getChildContext: function() {
        return {
            muiTheme: styles.getMuiTheme()
        }
    },
    render: function() {
        const timeComponent = React.createElement(TimePicker, props);
        const dateComponent = React.createElement(DatePicker, props);
        return React.createElement("div", {}, timeComponent, dateComponent);
    }
});

const form = React.createElement(Root, {});
const root = document.createElement("div");
window.onload = function() {
    document.body.appendChild(root);
    ReactDOM.render(form, root);
}
```
```json
"formsy-material-ui": "^0.4.2",
"formsy-react": "^0.18.0",
"material-ui": "0.15.0-beta.2",
"react": "^15.0.2",
"react-addons-create-fragment": "^15.0.2",
"react-dom": "^15.0.0",
"react-tap-event-plugin": "^1.0.0"
```

**Comment by mbrookes** [comment] 2016-05-10 13:55
@smithjessk Since you can reproduce without formsy-material-ui present, it isn't an FMUI bug. Closing this.

**Closed by mbrookes** 2016-05-10 13:55 UTC
