### ISSUE TITLE
Checkbox not updating

### ISSUE THREAD

**Issue by DriesS** [mbrookes/formsy-material-ui#55] opened 2016-02-27 15:09 UTC
When using the normal MUI Checkbox component the toggling of the checkbox is working perfect. When using the FormsyCheckbox component the toggling isn't working an the component stays in the original state.

I'm using material-ui@0.14.4 and formsy-material-ui@0.3.8

**Comment by mbrookes** [comment] 2016-02-27 16:14
I've updated formsy-mui-demo to current versions (material-ui@0.14.4 and formsy-material-ui@0.3.8), (which I should have done sooner!), and can't reproduce this issue.

Can you post or link to your code?

**Comment by DriesS** [comment] 2016-02-27 16:37
@mbrookes I can't share the whole project but I extracted the files that are involved.
I use redux and the component is rendered under route App -> Settings -> Network.

The form that is rendered you can find in Network.js.
When clicking on the checkbox I have some animation that illustrate the click but nothing is changing.

Here you find my gist : https://gist.github.com/DriesS/4c8d799e87cca7794a38

**Comment by mbrookes** [comment] 2016-02-27 16:55
I don't know why that doesn't work, sorry. You might find the chrome React devtool helps you diagnose.

**Comment by DriesS** [comment] 2016-02-28 10:20
@mbrookes did some further investigation and it looks like the value received in handleValueChange is always true or false ( depending how I set defaultChecked ).

` handleValueChange: function handleValueChange(event, value) {
    this.setValue(value);
    if (this.props.onChange) this.props.onChange(event, value);
  },`

Any idea why the value that I receive is always the initial value?

**Comment by mbrookes** [comment] 2016-02-29 11:02
What version of MAterial-UI are you running, and could this be related? https://github.com/callemall/material-ui/issues/2983

**Comment by DriesS** [comment] 2016-02-29 11:41
@mbrookes material-ui@0.14.4

**Comment by mbrookes** [comment] 2016-02-29 11:45
Mmm, okay, no 0.14.4 is fine here. Might be worth you trying 0.15.0-alpha.1 just in case.

**Comment by DriesS** [comment] 2016-03-01 14:56
@mbrookes another important detail I found out is that I have this bug only in chrome. Don't have this issue in Firefox and Safari.

**Comment by mbrookes** [comment] 2016-03-01 15:02
I'm testing Chrom (OS X). Weird!

**Comment by TintypeMolly** [comment] 2016-03-02 00:52
I'm experiencing the same issue, too.
```
Chrome	48.0.2564.116 (공식 빌드) m (32비트)
revision	700a0e589ecfa7e0f65cace17e2f75470c4adf9d-refs/branch-heads/2564@{#706}
OS	Windows 
Blink	537.36 (@700a0e589ecfa7e0f65cace17e2f75470c4adf9d)
JavaScript	V8 4.8.271.20
Flash	20.0.0.306
userAgent	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36
```

**Comment by TintypeMolly** [comment] 2016-03-02 00:59
```
Microsoft Edge 25.10586.0.0
Microsoft EdgeHTML 13.10586
```
It happens to Edge, too.
And I tested these two on Windows 10.

**Comment by TintypeMolly** [comment] 2016-03-02 06:59
This seems like a little tricky problem.
```node
handleValueChange: function handleValueChange(event, value) {
  console.log(value);
  this.setValue(value);
  if (this.props.onChange) this.props.onChange(event, value);
},
```
![mac_chrome](https://cloud.githubusercontent.com/assets/2056635/13452577/695beb28-e08c-11e5-905b-a6d39964afeb.gif)

Like this, This `value` argument is given as the value of the checkbox **before it was clicked** for Chrome on both Windows 10 and Mac OS X El Capitan.

So I should have override this function to be like this
```node
handleValueChange: function handleValueChange(event, value) {
  this.setValue(!value);
  if (this.props.onChange) this.props.onChange(event, !value);
},
```

But this time, this didn't work for Safari and Firefox.

I tried several os's and browsers and this is the result with `"material-ui@0.14.4"`.

```
OS                    | Browser    | Worked
Windows 10            | Chrome     | X
Windows 10            | Edge       | X
Mac OS X El Capitan   | Chrome     | X
Mac OS X El Capitan   | Safari     | O
Mac OS X El Capitan   | Firefox    | O
```

I followed the codes with `onChange` into the `enhanced-button.jsx`,

and I'm suspecting that this function works differently among browsers.

(from https://github.com/callemall/material-ui/blob/v0.14.4/src/enhanced-switch.jsx#L235)

```
_handleChange(e) {
  this._tabPressed = false;
  this.setState({
    isKeyboardFocused: false,
  });

  let isInputChecked = ReactDOM.findDOMNode(this.refs.checkbox).checked;

  if (!this.props.hasOwnProperty('checked')) {
    this.props.onParentShouldUpdate(isInputChecked);
  }
  if (this.props.onSwitch) {
    this.props.onSwitch(e, isInputChecked);
  }
},
```

I will look into it when I got home.

I need some comments and helps because I started node just a week ago.

**Comment by mbrookes** [comment] 2016-03-02 12:18
@TintypeMolly Thanks for the detailed analysis!.

@alitaheri - sorry to bother you, but could use your brains on this one!

**Comment by alitaheri** [comment] 2016-03-02 13:22
Hmm I'm guessing this is a race condition. I wonder what would happen if `_handleChange` was differed. can someone try: 
```js
_handleChange(e) {
  this._tabPressed = false;
  this.setState({
    isKeyboardFocused: false,
  });
  setTimeout(() => {
    let isInputChecked = ReactDOM.findDOMNode(this.refs.checkbox).checked;

    if (!this.props.hasOwnProperty('checked')) {
      this.props.onParentShouldUpdate(isInputChecked);
    }
    if (this.props.onSwitch) {
      this.props.onSwitch(e, isInputChecked);
    }
  });
},
```

at the mui's source code?  https://github.com/callemall/material-ui/blob/v0.14.4/src/enhanced-switch.jsx#L235

**Comment by alitaheri** [comment] 2016-03-02 13:27
the workaround would to to manually maintain the `checked` value. https://github.com/mbrookes/formsy-material-ui/blob/master/src/FormsyCheckbox.jsx can have a state to toggle handle `this.state.checked` whenever `handleValueChange` is called. I'm this is material-ui related, but for now that might work around this issue.

**Comment by mbrookes** [comment] 2016-03-02 13:33
Thanks @alitaheri, appreciate the input. If we can fix this at source, that would be preferable. 

I can't test here, since it works for me across all browsers, but hopefully @TintypeMolly and @DriesS can try your _handleChange fix.

**Comment by alitaheri** [comment] 2016-03-02 13:39
The EnhancedSwitch component needs total rework O.O

**Comment by TintypeMolly** [comment] 2016-03-02 14:49
>  toggle handle this.state.checked whenever handleValueChange is called

That saved my day. Thanks @alitaheri

Hope `EnhancedSwitch` can be fixed soon :+1:

**Comment by alitaheri** [comment] 2016-03-02 15:08
Glad I could help. can anyone confirm whether my proposed solution for material-ui can work? :sweat_smile: I can't do it my self without having to learn formsy and this library, as this issue is only raised with this library :sweat_smile:

**Comment by TintypeMolly** [comment] 2016-03-02 16:23
below worked for me.
```node
import React from 'react';
import Formsy from 'formsy-react';
import Checkbox from 'material-ui/lib/checkbox';
import { _setMuiComponentAndMaybeFocus } from 'formsy-material-ui/lib/utils';

let FormsyCheckbox = React.createClass({
  mixins: [ Formsy.Mixin ],

  propTypes: {
    name: React.PropTypes.string.isRequired
  },

  handleValueChange: function (event, _value) {
    const value = !this.getValue();
    this.setValue(value);
    if (this.props.onChange) this.props.onChange(event, value);
  },

  componentDidMount: function () {
    this.setValue(this._muiComponent.isChecked());
  },

  _setMuiComponentAndMaybeFocus: _setMuiComponentAndMaybeFocus,

  render: function () {
    return (
      <Checkbox
        {...this.props}
        ref={this._setMuiComponentAndMaybeFocus}
        onCheck={this.handleValueChange}
        checked={this.getValue()}
      />
    );
  }
});

module.exports = FormsyCheckbox;
```

**Comment by DriesS** [comment] 2016-03-02 17:25
@TintypeMolly thanks, is working here also.

**Comment by mbrookes** [comment] 2016-03-02 18:04
Could one of you please check whether [this](https://github.com/mbrookes/formsy-material-ui/issues/55#issuecomment-191236749) works so we can fix it at source?

**Comment by DriesS** [comment] 2016-03-02 19:41
@mbrookes changing the code of _handleChange isn't working here.

**Comment by mbrookes** [comment] 2016-03-05 22:03
Closing this since it's a MUI issue. I believe EnhancedButton is getting an overhaul, in which case hopefully this will be be fixed. In the meantime, glad @alitaheri's workaround helps. Thanks @alitaheri!

**Closed by mbrookes** 2016-03-05 22:03 UTC

**Comment by alitaheri** [comment] 2016-03-06 17:33
Anytime ( ^_^ )

**Comment by leonardoss** [comment] 2017-03-23 18:15
using react-starter-kit same problem until change change our BrowserSync config `ghostMode: false`

...and...worked... \o/
